import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { OnboardingProvider } from '@/lib/utils/context/onboardingContext';
import { WeatherProvider } from '@/lib/utils/context/weatherContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <OnboardingProvider>
      <WeatherProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </WeatherProvider>
    </OnboardingProvider>
  );
}
